### ISSUE TITLE
Add JsonNamingPolicy.PascalCase

### ISSUE THREAD

**Issue by cmeeren** [Tarmil/FSharp.SystemTextJson#113]
Noticed that JsonNamingPolicy was added, but only had the single case `CamelCase`. Would it be easy to add `PascalCase`?

**Comment by Tarmil** [comment]
This type is from the base library System.Text.Json, so I guess this should be suggested in the dotnet/runtime repo.

**Comment by cmeeren** [comment]
Oh, I didn't see that. Thanks for the clarification!
