### ISSUE TITLE
How to get the behaviour before breaking change #123 ?

### ISSUE THREAD

**Issue by SamuelBerger** [Tarmil/FSharp.SystemTextJson#138]
While updating to release version, our CI hits the breaking change #123 :(

Is there a way to configure the old behaviour:

- serialize None / ValueNone properties
- deserialize **missing** option / voption properties to None / ValueNone

IgnoreNullValues = true or DefaultIgnoreCondition = WhenWritingNull affects **serializing** as well.

Am I missing a trick (without changing all option properties to Skippable)?

(Throwing an exception for missing non option record properties is pure gold, so allowNullFields would never be an option.)

If there isn't a way to get the old behaviour, would a configuration `optionFieldsSkippable` be considered an improvement to the library?

**Comment by ly29** [comment]
While I understand this change I think the previous default was the sane behavior and having expectations like built in is wrong.

So while I look into an replacement library, if any, it would be nice that the previous behaviour was at least an option.

**Comment by nordfjord** [comment]
I am also surprised by this breaking change.

```fsharp
#r "nuget: FSharp.SystemTextJson"

open System.Text.Json
open System.Text.Json.Serialization

let opts = JsonSerializerOptions()
opts.Converters.Add(JsonFSharpConverter())

let body = JsonSerializer.Deserialize<{| name: string |}>("{}")

printfn "%A" body
```

In my mind this should throw an error. Before the breaking change this library was pure gold as I could trust that I wasn't allowing nulls to creep in at the edges.

**Comment by Tarmil** [comment]
Yes, I see that this is a common request. I agree that we should add an option to have the previous behavior without needing IgnoreNullValues/DefaultIgnoreCondition.

**Comment by Tarmil** [comment]
The new option SkippableOptionFields was added in v1.1 for this use case. https://github.com/Tarmil/FSharp.SystemTextJson/blob/master/docs/Customizing.md#skippable-option-fields

**Comment by SamuelBerger** [comment]
🤩Thank you @Tarmil ! You're the best!
