### ISSUE TITLE
Don't use case/fields with option

### ISSUE THREAD

**Issue by cmeeren** [Tarmil/FSharp.SystemTextJson#16]
It seems that `option`-wrapped types are serialized just like any other union, e.g. serializing `Some 2` gives `{"Case":"Some","Fields":[2]}`. It would be better if `option` was simply unwrapped entirely, i.e. `Some 2` serializes to `2`. See e.g. [FSharpLu.Json](https://github.com/Microsoft/fsharplu/wiki/fsharplu.json).

**Comment by Tarmil** [comment]
We've discussed this a bit in #6. The inconvenient is that it is technically less expressive, since it can't distinguish between `Some null` and `None`. Still, I agree that it's a better format in the vast majority of cases, and should be implemented and made the default.

**Comment by cmeeren** [comment]
I can't immediately think of any situations where one would want anything deserialized to `Some null`. But I think FSharpLu.Json has special handling of `_ option option`, making this possible. You could do the same if you want.

**Comment by lfr** [comment]
I got my hopes up when I saw that this library was a thing, but option not serializing to value or null is a non-starter for my usage :(
