### ISSUE TITLE
[StructuralComparison] for `Skippable`

### ISSUE THREAD

**Issue by xperiandri** [Tarmil/FSharp.SystemTextJson#163]
Add `[<StructuralComparison>]` attribute to `Skippable` type

**Comment by Tarmil** [comment]
What would this enable? It is already possible to do eg `Skip < Include 3`, with the expected result.

**Comment by xperiandri** [comment]
It will allow you to pass another type that has `StructuralComparison` attribute. Otherwise it is prohibited

**Comment by Tarmil** [comment]
Released in v1.2.
