### ISSUE TITLE
Skippable fields deserializing all missing option fields as null

### ISSUE THREAD

**Issue by nkosi23** [Tarmil/FSharp.SystemTextJson#189]
For some reason, while `.WithSkippableOptionFields(SkippableOptionFields.Always, deserializeNullAsNone = true)` prevents an exception from being raised when the field of a record is not present in the JSON being deserialized, all the fields of type option are deserialized as null instead of None

The only options I have are:

```fsharp
JsonFSharpOptions
            .Default()
            .WithIncludeRecordProperties()
            .WithUnionNamedFields()
            .WithSkippableOptionFields(SkippableOptionFields.Always, deserializeNullAsNone = true)
```

There is nothing exotic with my setup, I am deserializing to nested record types and discriminated unions (using custom JsonConverters) looking like the below:

```fsharp
type PlaceOrderCommand =
    {
        Name: NonEmptyString
        ContactDetails: CustomerContactDetails
        SomeString: NonEmptyString
        Amount: decimal
        SomeCountry: CountryOfInvestment
        SomeNumber: int option
```

Here, SomeNumber is null and the problem is present with all options being deserialized including in nested types. The whole application is affected.

**Comment by Tarmil** [comment]
Ah, indeed None is represented as null in the dotnet runtime. It would be nice if the debugger knew about it and displayed "None", but unfortunately it doesn't. Glad to see you figured out your issue!
