### ISSUE TITLE
JsonUnionEncoding.FSharpLuLike mismatch with fsharplu for single field union cases

### ISSUE THREAD

**Issue by johlrich** [Tarmil/FSharp.SystemTextJson#32]
There's a mismatch on the encoding for union cases with a single field when using `JsonUnionEncoding.FSharpLuLike`. In cases where field count = 1 FSharpLu will just serialize the object instead an array with the one object.

Example for `type SingleFieldCase = Single of string`

Current FSharpLuLike encoding: `{"Single":["hi"]}`

Actual FSharpLu encoding: `{
  "Single": "hi"
}`

I was not sure what the best way to approach this would be wrt affecting other encoding options. Happy to help implement any acceptable changes as needed.

**Comment by Tarmil** [comment]
Good catch! I think a good way to fix this would be to add an option to the `JsonUnionEncoding` enum, something like `SuccintSingleFieldUnions = 0x10_00`, that enables this behavior, and then `FSharpLuLike` would be `0x16_02`.
