### ISSUE TITLE
Spelling of JsonUnionEncoding.SuccintOption

### ISSUE THREAD

**Issue by mbuhot** [Tarmil/FSharp.SystemTextJson#34]
Is there a typo in the `JsonUnionEncoding.SuccintOption` flag, should it be `JsonUnionEncoding.SuccinctOption` ?

**Comment by Tarmil** [comment]
Ouch 😬 I was about to say "my French is showing", but it's actually spelled like that in French too...

It seems we can't put an `Obsolete` attribute on an enum case, so this will have to be a breaking change.

**Comment by Tarmil** [comment]
Per #38 I decided to rename this option `UnwrapOption`. The existing `SuccintOption` (including typo) remains, to avoid a breaking change.
