### ISSUE TITLE
Prevent nulls in non-option fields?

### ISSUE THREAD

**Issue by drhumlen** [Tarmil/FSharp.SystemTextJson#35]
Is there a way to prevent System.Text.Json from inserting `null`s at every opportunity? 

It seems like whenever a value is missing in the incoming json (either the field is missing, or explicititly a null from the client), it will just fill in a `null` and be happy. This leads to disastrous `NullReferenceException: Object reference not set to an instance of an object.` in our F# code since F# doesn't expect nulls at every corner.

The only time I want to allow a null or a missing field is if the field is of the (F#) `option` type.

Any advice?

**Comment by cmeeren** [comment]
I just came here to request the same. 👍 This would help me immensely.

**Comment by drhumlen** [comment]
My current workaround is to attach `[<Requried>]` attribute to each field in every record in my program. But that's very polluting and easy to forget when you make a new type. It would be nice to have it do the obvious thing in F# and not force in nulls where it shouldn't be possible. The F# compiler doesn't even allow you to _look for_ nulls because it insists that it's impossible for the field to be null :joy: Yet it is...

**Comment by cmeeren** [comment]
What attribute is that, and what does it do? I can't find it in `System.Text.Json`.

You probably already know, but just in case you don't - you can always check for nulls by boxing first: `isNull (box myObj)`

**Comment by drhumlen** [comment]
Had a go at a naive implementation: https://github.com/Tarmil/FSharp.SystemTextJson/pull/36  

Feedback is very welcome 😄

**Comment by drhumlen** [comment]
@cmeeren : it's found inside `open System.ComponentModel.DataAnnotations`
