### ISSUE TITLE
Map<string, _> where the string-key has a unit of measure doesn't (de)serialize correctly

### ISSUE THREAD

**Issue by drhumlen** [Tarmil/FSharp.SystemTextJson#40]
We use [FSharp.UMX](https://github.com/fsprojects/FSharp.UMX) to add some type-safety/specificity to our primitive types – like `string`.

```
[<Measure>] type userId

let usersAge: Map<string<userId>, int> = Map [%"user1", 30; %"user2", 40]
```

However it doesn't serialize as I'd hope: `{"user1": 30, "user2": 40}`, but instead as `[["user1", 30], "user2", 40]`

I've looked at the code here:
```F#
    static member internal CreateConverter(typeToConvert: Type) =
        let genArgs = typeToConvert.GetGenericArguments()
        let ty =
            if genArgs.[0] = typeof<string> then
                typedefof<JsonStringMapConverter<_>>
                    .MakeGenericType([|genArgs.[1]|])
```

Is there anything we can do to get the un-tagged version of the type so that it deserializes correctly?

Something like:

`if genArgs.[0].UnderlyingSystemType = typeof<string> then` ?

**Comment by drhumlen** [comment]
Upon further investigation it seems like the problem was caused by the tagged type being a Guid, and not a string as thought initially.

Perhaps there should be an issue created for using Guids as key in a map though?

**Comment by bartelink** [comment]
I believe this to be a [general issue with STJ](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#support-dictionary-with-non-string-key)

(In `Newtonsoft`, TypeConverters can be used as well as the more direct Conversion route (pretty sure that's not on the roadmap for STJ, and would not particularly want it to be).

For me, using `FSharp.UMX` with `Guid`s is a slightly dangerous thing - with `Guid`'s you have the `"N"` (aka _no dashes_) rendering vs the default. Thus I'd tend to employ a Converter, and then manage the value (post conversion) as canonicalized string like [this]( https://github.com/jet/FsCodec/blob/35ba5d7bc55de54655b774eb0b6e75f0714928c0/tests/FsCodec.NewtonsoftJson.Tests/PicklerTests.fs#L25-L41) - though probably as a ValueType in an STJ world
