### ISSUE TITLE
Converting array of array or list of lists

### ISSUE THREAD

**Issue by deeptowncitizen** [Tarmil/FSharp.SystemTextJson#55]
This package contains F# lists converter. But it does not work with included arrays:

```
type MyType () = 
    member val Items: int array array = [||] with get, set
```

for such JSON
```
"{ \"items\": [[1, 2, 3], [4, 5, 6]] }"
```

This will fail with 
```
System.NotSupportedException: Collection was of a fixed size
```

**Comment by mbuhot** [comment]
@deeptowncitizen does that example work with C#? 
It looks like the same error as [this issue](https://github.com/dotnet/runtime/issues/29843) fixed by [this PR](https://github.com/dotnet/corefx/pull/39442), but I'm not sure if that fix is in .net core 3.1, or we have to wait for .net 5.0.
