### ISSUE TITLE
Changelog for v0.14?

### ISSUE THREAD

**Issue by cmeeren** [Tarmil/FSharp.SystemTextJson#74]
I don't see 0.14 in the changelog; could it be added?

**Comment by Tarmil** [comment]
Yes indeed. It is [in the release](https://github.com/Tarmil/FSharp.SystemTextJson/releases/tag/v0.14) but I forgot to add it to the changelog.

**Comment by cmeeren** [comment]
Ah, thanks! I saw `CHANGELOG.md` and didn't think to check for GH releases.

**Comment by Tarmil** [comment]
Okay, it's now merged!
