### ISSUE TITLE
String-keyed Map output like as Dictionary

### ISSUE THREAD

**Issue by akhansari** [Tarmil/FSharp.SystemTextJson#82]
I wonder why they haven't the same output.
Just curious what's the reason behind this?

Is there any possibility to have the same, Map like Dictionary?

**Comment by Tarmil** [comment]
The output should be a JSON object in both cases. The only difference is the order of the keys: `Map` is sorted by comparing the keys, whereas `Dictionary` is sorted in an arbitrary order that is based on its internal implementation.

```fsharp
JsonSerializer.Serialize(Map ["b", 1; "a", 2], options) // --> {"a":2,"b":1}
JsonSerializer.Serialize(dict ["b", 1; "a", 2], options) // --> {"b":1,"a":2}
```

 Is this what you mean? Or do you have other differences?

**Comment by akhansari** [comment]
Thanks Tarmil for the explanation..
My bad, it's only non string-keyed [Map](https://github.com/Tarmil/FSharp.SystemTextJson/blob/master/docs/Format.md#maps) that is serialized to an array of arrays.
It's perfect because we can have interoperability between other dictionary types and Map.
