### ISSUE TITLE
Consider caching the result of `FSharpType.IsRecord` and `FSharpType.IsUnion`

### ISSUE THREAD

**Issue by baronfel** [Tarmil/FSharp.SystemTextJson#9]
Per the implementation [here](https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/reflect.fs#L620-L629) and [here](https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/reflect.fs#L242-L253), these functions have to use reflection to get type custom attributes, deconstruct them, and do some additional processing. Would it make sense to build a dict of `hash(type.FullName) -> bool` and check that before delegating to the underlying function for the `IsRecord/IsUnion` checks that are done as part of `CanConvert` for the serializers?

**Comment by Tarmil** [comment]
Good question, I don't know if `CanConvert` is called repetitively or only during warmup.

**Comment by baronfel** [comment]
From what I was reading in the [JsonPropertyInfo-createing code](https://github.com/dotnet/corefx/blob/69df8abea7bd02fcaa47befb6f9722bf2908e6ac/src/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.AddProperty.cs#L113-L134), CanConvert will eventually be called for every property of every type that you want to serialize.
