### ISSUE TITLE
UntrustedRoot: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by james-d-hasselman** [Tarmil/FSharp.SystemTextJson#94]
OS: Arch Linux
.NET Version: .NET 5.0 (.NET Core)

After installing the package using the .NET CLI instructions found here https://www.nuget.org/packages/FSharp.SystemTextJson I get three errors when running "dotnet restore" or "dotnet build":

error NU3028: Package 'System.Text.Json 4.6.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
error NU3037: Package 'System.Text.Json 4.6.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
error NU3028: Package 'System.Text.Json 4.6.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain

Do you know what I can do to resolve this?

**Comment by baronfel** [comment]
You're hitting [this](https://github.com/NuGet/Home/issues/10491) nuget issue, please check out the resolution steps there. This issue took the .net world by storm a couple months ago all over the place.

**Comment by james-d-hasselman** [comment]
Thanks, that got me pointed in the right direction. The workaround described in this [Arch bug report](https://bugs.archlinux.org/task/70095) fixed the problem for me.
